services:
  db:
    image: postgres:14.2
    ports:
      - '5432:5432'
    volumes:
      - 'lunch-together-postgres:/var/modules/lunch-together/postgresql'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
volumes:
  lunch-together-postgres: