@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "Office Employee", "A member of a group or company")
Container(applicationAlias, "Mobile Application", "React Native", "Provides UI interface for user to hold a meal with others")
System(ltSystemAlias, "Lunch Together System", "Provides services to help user making a meal")
System(notificationSystemAlias, "Notification System", "Notify information for user's UI interface, sms, email")

Rel(personAlias, applicationAlias, "Uses", "View , make a meal with others")
Rel(applicationAlias, ltSystemAlias, "HTTPs", "GraphQL query, mutation, subscription")
Rel(notificationSystemAlias, applicationAlias, "HTTPs", "Push notification")
Rel(notificationSystemAlias, personAlias, "HTTPs", "Email, SMS")
Rel(ltSystemAlias, notificationSystemAlias, "HTTPs", "", "" )
@enduml